import { expect, test, type Page } from '@playwright/test'

async function enterAsGuest(page: Page) {
  await page.goto('/?role=leader')
  const chooser = page.getByRole('dialog', { name: 'Choose your role' })
  await expect(chooser).toBeVisible()
  await chooser.getByRole('button', { name: 'Continue as Guest', exact: true }).click()
  await expect(chooser).toBeHidden()
  // Guest entry returns to the default home. The existing role URL selects a public lens.
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/?role=leader')
  await expect(page.getByRole('heading', { name: 'Which condition does your group serve?' })).toBeVisible()
}

test('the real v2 guest journey retains STXBP1 mechanisms, cited connections and its action tracker', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await enterAsGuest(page)
  await page.getByTestId('hero-search').fill('STXBP1')
  const condition = page.getByRole('option', { name: /developmental and epileptic encephalopathy, 4/ })
  await expect(condition).toContainText('STXBP1')
  await condition.click()
  await expect(page).toHaveURL(/focus=dis_stxbp1/)
  await expect(page.getByTestId('disease-title')).toHaveText('developmental and epileptic encephalopathy, 4')
  const conditionURL = page.url()
  await expect(page.getByRole('link', { name: 'STXBP1 Foundation', exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Impaired inhibitory synaptic neurotransmission', exact: true }).click()
  await expect(page).toHaveURL(/\/node\/mech_synaptic_release/)
  await expect(page.getByRole('heading', { name: 'Impaired inhibitory synaptic neurotransmission', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Open evidence: PMID/ }).first().click()
  const mechanismEvidence = page.getByRole('dialog', { name: 'Evidence', exact: true })
  await expect(mechanismEvidence).toBeVisible()
  await expect(mechanismEvidence.locator('a[href*="pubmed.ncbi.nlm.nih.gov"]').first()).toBeVisible()
  await expect(mechanismEvidence.locator('blockquote').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(mechanismEvidence).toBeHidden()

  await page.goto(conditionURL)
  const investigatorConnection = page.getByTestId('connection-list').locator('li').filter({ hasText: 'Shared investigator' }).first()
  await expect(investigatorConnection).toBeVisible()
  await investigatorConnection.getByRole('link', { name: 'Why connected', exact: true }).click()
  await expect(page).toHaveURL(/\/route\?.*from=dis_stxbp1/)
  await expect(page.getByTestId('route-summary')).toContainText('Network overlap')
  await expect(page.getByTestId('route-summary')).toContainText('Inferred')
  await expect(page.getByTestId('route-steps').first().locator(':scope > li')).toHaveCount(2)
  await page.getByRole('button', { name: /^Open evidence: RePORTER/ }).first().click()
  const routeEvidence = page.getByRole('dialog', { name: 'Evidence', exact: true })
  await expect(routeEvidence).toBeVisible()
  await expect(routeEvidence.locator('a[href^="https://reporter.nih.gov/project-details/"]').first()).toBeVisible()
  await expect(routeEvidence.locator('blockquote').first()).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByTestId('to-action').click()
  await expect(page).toHaveURL(/\/action\/dis_stxbp1/)
  await expect(page.getByRole('heading', { name: 'Action plan', exact: true })).toBeVisible()
  await expect(page.getByTestId('plan-background')).toContainText('Shared people, not shared biology')
  const progress = page.getByTestId('plan-progress')
  await expect(progress).toContainText(/^0 of \d+ tasks done/)
  const active = Number((await progress.innerText()).match(/0 of (\d+) tasks done/)?.[1])
  expect(active).toBeGreaterThan(0)
  await page.getByTestId('workflow').getByRole('checkbox').first().click()
  await expect(progress).toContainText(`1 of ${active} tasks done`)
  await page.reload()
  await expect(progress).toContainText(`1 of ${active} tasks done`)

  await page.getByTestId('add-task').getByRole('textbox').fill('Review the cited STXBP1 resources with our group')
  await page.getByTestId('add-task').getByRole('button', { name: 'Add task', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Review the cited STXBP1 resources with our group', exact: true })).toBeVisible()
  await page.getByTestId('all-plans').click()
  await expect(page.getByTestId('your-plans')).toContainText('developmental and epileptic encephalopathy, 4')
  await expect(page.getByTestId('your-plans')).toContainText(`1 of ${active + 1} done`)
  expect(errors).toEqual([])
})

test('guest search preserves an honest answer for an unindexed query', async ({ page }) => {
  await enterAsGuest(page)
  const query = 'unindexed-condition-account-regression'
  await page.getByTestId('hero-search').fill(query)
  await page.getByTestId('hero-search').press('Enter')
  await expect(page).toHaveURL(/\/search\?.*q=unindexed-condition-account-regression/)
  const noRoute = page.getByTestId('no-route')
  await expect(noRoute).toContainText(`“${query}” is not in the atlas`)
  await expect(noRoute).toContainText('What was searched')
  await expect(noRoute).toContainText('What is missing')
  await expect(noRoute).toContainText('What would answer it')
  await expect(page.getByTestId('search-results')).toHaveCount(0)
})

test('a known condition without a supported biological route retains its no-route explanation', async ({ page }) => {
  await enterAsGuest(page)
  await page.goto('/action/dis_kcnq2?role=leader')
  const noRoute = page.getByTestId('no-route')
  await expect(noRoute).toContainText('No supported route')
  await expect(noRoute).toContainText('What was searched')
  await expect(noRoute).toContainText('What is missing')
  await expect(noRoute).toContainText('Common symptoms are not enough to suggest shared biology')
  await expect(page.getByRole('heading', { name: 'Action plan', exact: true })).toBeVisible()
})
